export type TenderStatus = "won" | "lost" | "pending";

export interface Tender {
  id: string;
  title: string;
  client: string;
  sector: string;
  status: TenderStatus;
  consultantsNeeded: number;
  price: number;
  tags: string[];
  similarityScore: number;
  submissionDate: string;
  responseDate: string;
  description: string;
  aiSummary: string;
  methodology: string;
  staffing: string;
  differentiators: string;
  duration: string;
  technologies: string[];
}

export const sectors = [
  "Énergie et utilities",
  "Transport et mobilités",
  "Banque et finance",
  "Services publics",
  "Protection sociale",
  "Retail et luxe",
  "Assurance",
  "Industrie",
  "Médias",
  "Santé",
];

export const allTags = [
  "Cloud", "IA", "Cybersécurité", "Data", "Agilité", "SAP", "ERP",
  "Transformation Digitale", "IoT", "Blockchain", "DevOps", "RGPD",
  "Stratégie", "PMO", "Change Management", "Infrastructure", "Jumeaux Numériques", "MLOps",
];

export const tenders: Tender[] = [
  {
    id: "AO-2025-001",
    title: "Modernisation du SI de gestion des ressources humaines",
    client: "Ministère des Armées",
    sector: "Services publics",
    status: "won",
    consultantsNeeded: 8,
    price: 2400000,
    tags: ["ERP", "SAP", "Change Management"],
    similarityScore: 92,
    submissionDate: "2025-01-15",
    responseDate: "2025-02-28",
    description: "Refonte complète du SIRH pour 45 000 agents civils et militaires.",
    aiSummary: "Projet de transformation du système d'information RH du Ministère des Armées. Périmètre : paie, gestion des carrières, formation, mobilité. Migration SAP HCM vers SAP SuccessFactors. 45 000 utilisateurs finaux.",
    methodology: "Approche Agile SAFe avec sprints de 3 semaines. Phase de cadrage (3 mois), conception (4 mois), réalisation (8 mois), recette (3 mois), déploiement progressif (6 mois).",
    staffing: "1 Directeur de Programme, 2 Chefs de Projet, 3 Consultants fonctionnels SAP, 1 Architecte SI, 1 Expert Change Management",
    differentiators: "Expérience de 15 projets SIRH dans le secteur public. Équipe certifiée SAP SuccessFactors. Méthodologie éprouvée de conduite du changement.",
    duration: "18 mois",
    technologies: ["Kubernetes", "AWS"],
  },
  {
    id: "AO-2025-002",
    title: "Plateforme de données temps réel pour la supervision ferroviaire",
    client: "SNCF Réseau",
    sector: "Transport et mobilités",
    status: "won",
    consultantsNeeded: 12,
    price: 3800000,
    tags: ["Data", "IoT", "Cloud", "IA"],
    similarityScore: 88,
    submissionDate: "2025-02-01",
    responseDate: "2025-03-15",
    description: "Conception d'une plateforme Big Data pour la supervision en temps réel du réseau ferroviaire français.",
    aiSummary: "Création d'un data lake temps réel ingérant les données de 30 000 capteurs IoT. Algorithmes prédictifs de maintenance. Dashboard de supervision pour 500 opérateurs.",
    methodology: "Architecture Data Mesh. Développement itératif avec MVP en 4 mois. Stack: Kafka, Spark, Databricks, Power BI.",
    staffing: "1 Lead Data Architect, 4 Data Engineers, 3 Data Scientists, 2 Développeurs Front, 1 Scrum Master, 1 Product Owner",
    differentiators: "Référence unique avec RTE sur un projet similaire. Expertise IoT industriel et traitement temps réel.",
    duration: "24 mois",
    technologies: ["SAP", "AWS"],
  },
  {
    id: "AO-2025-003",
    title: "Audit de cybersécurité et mise en conformité NIS2",
    client: "Airbus Defence & Space",
    sector: "Services publics",
    status: "won",
    consultantsNeeded: 5,
    price: 890000,
    tags: ["Cybersécurité", "RGPD", "Stratégie"],
    similarityScore: 95,
    submissionDate: "2025-01-20",
    responseDate: "2025-03-01",
    description: "Audit complet et plan de remédiation pour conformité NIS2 sur 12 sites européens.",
    aiSummary: "Audit de maturité cyber sur 12 sites. Gap analysis NIS2. Plan de remédiation priorisé. Formation de 200 collaborateurs clés.",
    methodology: "Framework NIST CSF + ISO 27001. Audit en 3 vagues géographiques. Rapport exécutif avec roadmap 18 mois.",
    staffing: "1 Directeur de Mission, 2 Auditeurs Cyber seniors, 1 Expert Conformité, 1 Formateur",
    differentiators: "Certification PASSI. 50+ audits NIS2 réalisés. Connaissance du secteur aéronautique et défense.",
    duration: "9 mois",
    technologies: ["GCP", "Docker"],
  },
  {
    id: "AO-2025-004",
    title: "Transformation digitale des services aux citoyens",
    client: "Métropole de Lyon",
    sector: "Services publics",
    status: "lost",
    consultantsNeeded: 6,
    price: 1200000,
    tags: ["Transformation Digitale", "Agilité", "Cloud"],
    similarityScore: 78,
    submissionDate: "2025-03-01",
    responseDate: "2025-04-15",
    description: "Dématérialisation de 150 démarches administratives et portail citoyen unifié.",
    aiSummary: "Portail unique pour 1.4M habitants. 150 démarches dématérialisées. Intégration FranceConnect. Chatbot IA pour l'orientation.",
    methodology: "Design Thinking + Agile Scrum. Co-conception avec usagers. Déploiement par lots de 30 démarches.",
    staffing: "1 Chef de Projet, 2 Consultants UX, 2 Développeurs Full-Stack, 1 Expert Intégration",
    differentiators: "Référence Ville de Paris. Expertise FranceConnect et dématérialisation.",
    duration: "18 mois",
    technologies: ["Databricks", "AWS"],
  },
  {
    id: "AO-2025-005",
    title: "Déploiement d'une solution de Smart Grid",
    client: "Enedis",
    sector: "Énergie et utilities",
    status: "won",
    consultantsNeeded: 10,
    price: 4500000,
    tags: ["IoT", "Data", "IA", "Infrastructure"],
    similarityScore: 85,
    submissionDate: "2025-02-10",
    responseDate: "2025-04-01",
    description: "Mise en place d'un réseau intelligent pour la gestion optimisée de la distribution électrique.",
    aiSummary: "Smart Grid pour 8 régions. 2M compteurs Linky intégrés. Algorithmes d'optimisation de la distribution. Réduction de 15% des pertes réseau.",
    methodology: "POC sur 2 régions puis déploiement national. Architecture microservices sur Azure. MLOps pour les modèles prédictifs.",
    staffing: "1 Program Manager, 2 Architectes Solution, 3 Développeurs, 2 Data Scientists, 1 Expert Énergie, 1 DevOps",
    differentiators: "Partenariat technologique avec Schneider Electric. Expertise unique en optimisation énergétique.",
    duration: "24 mois",
    technologies: ["SAP", "React"],
  },
  {
    id: "AO-2025-006",
    title: "Refonte du dossier patient informatisé",
    client: "AP-HP",
    sector: "Santé",
    status: "lost",
    consultantsNeeded: 15,
    price: 6200000,
    tags: ["ERP", "Cloud", "RGPD", "Change Management"],
    similarityScore: 72,
    submissionDate: "2025-03-15",
    responseDate: "2025-05-01",
    description: "Migration du DPI vers une solution cloud souveraine pour 39 hôpitaux.",
    aiSummary: "Migration DPI pour 39 établissements, 100 000 professionnels de santé. Cloud souverain SecNumCloud. Interopérabilité HL7 FHIR.",
    methodology: "Méthode en V adaptée au contexte hospitalier. Pilote sur 3 hôpitaux. Déploiement sur 18 mois.",
    staffing: "2 Directeurs de Programme, 4 Consultants Santé, 3 Architectes, 4 Développeurs, 2 Experts Change",
    differentiators: "25 projets hospitaliers. Certification HDS. Expertise HL7 FHIR.",
    duration: "6 mois",
    technologies: ["Databricks", "SAP"],
  },
  {
    id: "AO-2025-007",
    title: "Migration cloud et DevOps pour le système bancaire",
    client: "BNP Paribas",
    sector: "Banque et finance",
    status: "won",
    consultantsNeeded: 8,
    price: 3200000,
    tags: ["Cloud", "DevOps", "Infrastructure", "Cybersécurité"],
    similarityScore: 90,
    submissionDate: "2025-01-25",
    responseDate: "2025-03-10",
    description: "Migration de 200 applications legacy vers un cloud privé avec pipeline CI/CD.",
    aiSummary: "Migration lift & shift puis refactoring de 200 applications. Cloud privé OpenShift. Pipeline CI/CD GitLab. Sécurité renforcée PCI DSS.",
    methodology: "Approche 6R (Rehost, Replatform, Refactor...). Vagues de 20 applications. Automatisation Terraform + Ansible.",
    staffing: "1 Cloud Architect Lead, 3 DevOps Engineers, 2 Développeurs, 1 Expert Sécurité, 1 Chef de Projet",
    differentiators: "100+ migrations cloud bancaires. Certification AWS + Azure + GCP. Expertise PCI DSS.",
    duration: "6 mois",
    technologies: ["GCP", "React"],
  },
  {
    id: "AO-2025-008",
    title: "Étude d'impact environnemental et reporting ESG",
    client: "TotalEnergies",
    sector: "Industrie",
    status: "pending",
    consultantsNeeded: 4,
    price: 680000,
    tags: ["Data", "Stratégie", "PMO"],
    similarityScore: 65,
    submissionDate: "2025-04-01",
    responseDate: "2025-05-15",
    description: "Mise en place d'un outil de reporting ESG automatisé conforme CSRD.",
    aiSummary: "Dashboard ESG temps réel. Collecte automatisée des données environnementales. Conformité CSRD et taxonomie européenne.",
    methodology: "Cadrage réglementaire CSRD. Cartographie des données ESG. Développement itératif du dashboard.",
    staffing: "1 Expert ESG, 1 Data Analyst, 1 Développeur BI, 1 Chef de Projet",
    differentiators: "Première référence CSRD en France. Double compétence data + RSE.",
    duration: "4 mois",
    technologies: ["Databricks"],
  },
  {
    id: "AO-2025-009",
    title: "Plateforme IA générative pour l'assistance juridique",
    client: "Ministère de la Justice",
    sector: "Services publics",
    status: "won",
    consultantsNeeded: 7,
    price: 1800000,
    tags: ["IA", "Cloud", "Data", "Transformation Digitale"],
    similarityScore: 82,
    submissionDate: "2025-02-20",
    responseDate: "2025-04-05",
    description: "Développement d'un assistant IA pour les magistrats basé sur la jurisprudence.",
    aiSummary: "RAG sur 2M décisions de justice. Assistant IA pour recherche juridique. LLM fine-tuné sur le droit français. Interface conversationnelle.",
    methodology: "Fine-tuning LLM Mistral. Architecture RAG avec vector store. Évaluation continue par des magistrats experts.",
    staffing: "1 Lead ML Engineer, 2 Data Scientists, 2 Développeurs Full-Stack, 1 Expert Juridique, 1 Product Owner",
    differentiators: "Équipe spécialisée NLP français. Référence IA générative avec l'ANSSI. Expertise LegalTech.",
    duration: "6 mois",
    technologies: ["GCP"],
  },
  {
    id: "AO-2025-010",
    title: "Programme de transformation Agile à l'échelle",
    client: "Thales",
    sector: "Services publics",
    status: "won",
    consultantsNeeded: 6,
    price: 1500000,
    tags: ["Agilité", "Change Management", "PMO", "Stratégie"],
    similarityScore: 88,
    submissionDate: "2025-03-05",
    responseDate: "2025-04-20",
    description: "Déploiement du framework SAFe sur 4 divisions et 2000 collaborateurs.",
    aiSummary: "Transformation Agile SAFe pour 4 divisions. Formation de 200 Scrum Masters et Product Owners. 50 Agile Release Trains.",
    methodology: "SAFe Implementation Roadmap. Formation certifiante. Coaching embarqué pendant 12 mois.",
    staffing: "1 SPC Lead, 2 Coachs Agile, 2 Formateurs certifiés, 1 Expert Change Management",
    differentiators: "15 transformations SAFe réussies. Équipe 100% certifiée SAFe. Connaissance du secteur Défense.",
    duration: "3 mois",
    technologies: ["Kubernetes", "Snowflake"],
  },
  {
    id: "AO-2025-011",
    title: "Blockchain pour la traçabilité de la chaîne logistique",
    client: "CMA CGM",
    sector: "Transport et mobilités",
    status: "lost",
    consultantsNeeded: 5,
    price: 950000,
    tags: ["Blockchain", "IoT", "Cloud"],
    similarityScore: 70,
    submissionDate: "2025-02-15",
    responseDate: "2025-03-30",
    description: "Solution blockchain pour le suivi en temps réel des conteneurs maritimes.",
    aiSummary: "Blockchain Hyperledger pour tracking de 500K conteneurs. Smart contracts pour douanes. Intégration avec systèmes portuaires.",
    methodology: "POC blockchain 3 mois. Pilot sur la ligne Asie-Europe. Déploiement mondial en 3 phases.",
    staffing: "1 Blockchain Architect, 2 Développeurs Solidity, 1 Expert Supply Chain, 1 Chef de Projet",
    differentiators: "Expertise Hyperledger Fabric. Référence traçabilité avec Carrefour.",
    duration: "3 mois",
    technologies: ["Snowflake", "Kubernetes"],
  },
  {
    id: "AO-2025-012",
    title: "Mise en conformité RGPD et gouvernance des données",
    client: "Groupe La Poste",
    sector: "Services publics",
    status: "won",
    consultantsNeeded: 4,
    price: 720000,
    tags: ["RGPD", "Data", "Stratégie"],
    similarityScore: 91,
    submissionDate: "2025-01-10",
    responseDate: "2025-02-25",
    description: "Programme de mise en conformité RGPD pour l'ensemble du Groupe La Poste.",
    aiSummary: "Cartographie de 3000 traitements de données. Mise en conformité RGPD. Data governance framework. DPO externalisé.",
    methodology: "Audit initial. Registre des traitements. PIA sur les traitements à risque. Sensibilisation de 50 000 collaborateurs.",
    staffing: "1 DPO Expert, 1 Juriste RGPD, 1 Consultant Data Governance, 1 Chef de Projet",
    differentiators: "500+ mises en conformité RGPD. Outil propriétaire de cartographie des traitements.",
    duration: "4 mois",
    technologies: ["Azure", "Docker"],
  },
  {
    id: "AO-2025-013",
    title: "Système de monitoring environnemental par satellite",
    client: "CNES",
    sector: "Industrie",
    status: "pending",
    consultantsNeeded: 9,
    price: 5100000,
    tags: ["IA", "Data", "Cloud", "IoT"],
    similarityScore: 76,
    submissionDate: "2025-04-10",
    responseDate: "2025-05-30",
    description: "Plateforme d'analyse d'images satellite pour le suivi de la déforestation et de la pollution.",
    aiSummary: "Computer Vision sur images Sentinel-2. Détection automatique de déforestation. Dashboard de suivi environnemental pour 20 pays.",
    methodology: "Deep Learning (U-Net, ResNet). Pipeline de traitement d'images sur GPU cloud. API REST pour intégration partenaires.",
    staffing: "2 ML Engineers, 2 Data Engineers, 2 Développeurs, 1 Expert Géospatial, 1 Chef de Projet, 1 DevOps",
    differentiators: "Expertise Computer Vision satellite. Partenariat ESA. Publications scientifiques dans le domaine.",
    duration: "9 mois",
    technologies: ["Azure", "Docker"],
  },
  {
    id: "AO-2025-014",
    title: "ERP SAP S/4HANA migration pour industrie pharmaceutique",
    client: "Sanofi",
    sector: "Santé",
    status: "won",
    consultantsNeeded: 14,
    price: 7800000,
    tags: ["SAP", "ERP", "Cloud", "Change Management"],
    similarityScore: 93,
    submissionDate: "2025-01-30",
    responseDate: "2025-03-20",
    description: "Migration SAP ECC vers S/4HANA pour 30 sites de production dans 15 pays.",
    aiSummary: "Migration brownfield SAP S/4HANA. 30 sites, 15 pays, 12 000 utilisateurs. Modules MM, PP, QM, FI/CO. Go-live en big bang par région.",
    methodology: "SAP Activate. Custom code remediation. Data migration avec LTMC. Hypercare 3 mois post go-live.",
    staffing: "2 Program Directors, 4 SAP Functional Leads, 3 ABAP Developers, 2 Basis Engineers, 2 Change Managers, 1 PMO",
    differentiators: "30+ migrations S/4HANA. Expertise pharma GxP. Équipe multilingue 8 nationalités.",
    duration: "3 mois",
    technologies: ["SAP", "Docker"],
  },
  {
    id: "AO-2025-015",
    title: "Stratégie data et lac de données pour l'assurance",
    client: "AXA France",
    sector: "Banque et finance",
    status: "lost",
    consultantsNeeded: 7,
    price: 2100000,
    tags: ["Data", "Cloud", "IA", "Stratégie"],
    similarityScore: 80,
    submissionDate: "2025-03-20",
    responseDate: "2025-05-05",
    description: "Définition de la stratégie data et construction d'un data lake unifié pour AXA France.",
    aiSummary: "Data strategy pour AXA France. Data lake sur Snowflake. 500 datasets unifiés. Self-service analytics pour 1000 utilisateurs.",
    methodology: "Data Strategy Framework propriétaire. Gouvernance DataOps. Catalogue de données Alation.",
    staffing: "1 Chief Data Strategist, 2 Data Architects, 2 Data Engineers, 1 Analytics Lead, 1 PMO",
    differentiators: "Expertise assurance et actuariat. 20+ data lakes construits. Partenariat Snowflake.",
    duration: "9 mois",
    technologies: ["SAP", "Snowflake"],
  },
  // --- Propositions concurrentes pour l'AO ENGIE-DSI-2025-089 ---
  {
    id: "AO-2025-016",
    title: "PowerForecast360 — IA & Digital Twin pour actifs EnR offshore",
    client: "ENGIE SA",
    sector: "Énergie et utilities",
    status: "lost",
    consultantsNeeded: 9,
    price: 1695961,
    tags: ["IA", "IoT", "Cloud", "Jumeaux Numériques", "Data"],
    similarityScore: 92,
    submissionDate: "2025-04-18",
    responseDate: "2025-05-15",
    description: "Proposition Assystem / Exodigo — Déploiement de jumeaux numériques haute-fidélité et plateforme IA pour les actifs renouvelables ENGIE. Architecture IoT Edge-Cloud souveraine et modèles IA prédiction de production offshore.",
    aiSummary: "Architecture IoT-Edge-Cloud Azure souveraine. Jumeaux numériques CFD haute-fidélité (Exodigo WindTwin). RMSE J+1 démontré à 3,4% sur 12 ans de données historiques. Maintenance prédictive offshore validée sur Dogger Bank (190 turbines, -38% pannes non planifiées). Optimisation trading day-ahead/intraday par reinforcement learning (+4,2% revenu, ref. Fécamp). Gain de production +3,1% sur Hornsea 2.",
    methodology: "PowerForecast360 — 8 phases sur 56 semaines. Phase 1 : Audit & Cartographie (Sem. 1-8). Phase 2 : Architecture IoT & Data Lake Azure (Sem. 9-14). Phase 3 : Jumeaux numériques pilote 3 parcs éoliens CFD+ML (Sem. 15-24). Phase 4 : Modèles IA prédiction v1 LSTM+TFT+XGBoost RMSE<3,5% (Sem. 25-32). Phase 5 : Maintenance prédictive offshore & onshore SAP PM (Sem. 33-40). Phase 6 : Dashboard opérationnel unifié temps réel (Sem. 40-46). Phase 7 : Formation & Documentation ENGIE (Sem. 46-52). Phase 8 : Clôture & Feuille de route 2026-2030 (Sem. 52-56).",
    staffing: "Hervé CHAUVIN (Directeur de mission Assystem, 18 ans, EnR offshore Ørsted/Vattenfall), Ran ILAN (Directeur technique Exodigo, 14 ans, Digital twin CFD offshore), Camille ROUSSEL (Chef de projet senior, 11 ans, PMP SAFe Azure), Alexis GIRARD (Architecte IoT & Data, 10 ans, SCADA offshore IEC 61968), Yuki TANAKA (Data Scientist Énergie, 8 ans, PhD ML TFT NWP offshore forecasting), Mathieu COLIN (Expert Jumeaux Numériques, 9 ans, OpenFOAM CFD MATLAB), Sirine HADJ (Experte Maintenance Prédictive, 8 ans, offshore vibration FMEA SAP PM), Thomas NGUYEN (MLOps/DevOps, 6 ans, Azure Kubernetes MLflow), Pauline BRUNET (Change & Formation, 7 ans, documentation EnR)",
    differentiators: "Tandem Assystem/Exodigo — spécialistes EnR offshore & Digital Twin. Références directement comparables : Dogger Bank 5,2 GW (-38% pannes), Hornsea 2 (+3,1% production), Fécamp offshore (+4,2% revenu trading). RMSE J+1 démontré à 3,4% sur grandes installations. Budget sous la fourchette basse de l'AO (1,70M€ HT). Plateforme Exodigo WindTwin SaaS déployée sur 15 GW mondiaux.",
    duration: "30 mois",
    technologies: ["Azure", "Kafka", "Kubernetes"],
  },
  {
    id: "AO-2025-017",
    title: "EnergyEdge — Accélération digitale des actifs renouvelables ENGIE",
    client: "ENGIE SA",
    sector: "Énergie et utilities",
    status: "won",
    consultantsNeeded: 8,
    price: 1784475,
    tags: ["IA", "IoT", "Cloud", "Data", "MLOps"],
    similarityScore: 75,
    submissionDate: "2025-04-18",
    responseDate: "2025-05-15",
    description: "Proposition Capgemini Invent — Accélération digitale des actifs EnR ENGIE avec la méthodologie EnergyEdge. Plateforme IoT-Edge-Cloud souveraine, jumeaux numériques Ansys et modèles IA spécialisés énergie.",
    aiSummary: "EnergyEdge — cadre propriétaire développé sur 20 projets dans 8 pays. Architecture IoT-Edge-Cloud Azure souveraine. Jumeaux numériques via Ansys Fluent (CFD) + ML calibration. RMSE J+1 cible 4,2%. Maintenance prédictive (vibration, thermique, SAP PM). Optimisation dispatch par reinforcement learning +3 à 5% revenu. Références : EDF Renouvelables (95 parcs, RMSE 4,1%), Vattenfall offshore (-28% pannes), Ørsted (12 parcs, +2,8%).",
    methodology: "EnergyEdge — 6 phases sur 52 semaines. Phase 1 : Audit & Roadmap digitale (Sem. 1-8). Phase 2 : Architecture IoT & Data Lake Azure IEC 61968 (Sem. 9-14). Phase 3 : Jumeaux numériques pilote 3 parcs éoliens Ansys+ML (Sem. 15-24). Phase 4 : IA production & trading LSTM XGBoost RL (Sem. 20-32). Phase 5 : Maintenance prédictive vibration thermique SAP PM (Sem. 28-40). Phase 6 : Déploiement & MLOps Go-live documentation (Sem. 38-52).",
    staffing: "Laurent FISCHER (VP Directeur de mission, 16 ans, EDF Vattenfall programme, 80%), Sophie ARNAUD (Chef de projet senior, 11 ans, PMP SAFe énergie renouvelable Azure, 100%), Marc DUVALIER (Architecte IoT & Data, 9 ans, Azure IoT Kafka IEC 61968 SCADA, 100%), Lin ZHANG (Data Scientist Énergie, 8 ans, PhD ML LSTM NWP PyTorch éolien, 80%), Éric BONNARD (Expert Jumeaux Numériques, 8 ans, Ansys Fluent Modelica CFD MATLAB, 80%), Fatima ZEROUALI (Experte Maintenance Prédictive, 7 ans, vibration CMMS SAP PM FMEA, 80%), Baptiste LEROY (DevOps/MLOps, 6 ans, Azure Kubernetes MLflow CI/CD, 80%), Juliette MORIN (Change Mgmt, 5 ans, formation documentation technique, 60%)",
    differentiators: "200 experts Énergie & Utilities. 15 GW de capacités renouvelables avec IA déployée. Méthodologie EnergyEdge éprouvée sur 20 projets. Références directes EDF Renouvelables, Vattenfall offshore, Ørsted. Centre d'Excellence Énergie & Utilities dédié. Cadre MLOps industrialisé pour pérennité des solutions.",
    duration: "30 mois",
    technologies: ["Azure", "Kafka", "Kubernetes"],
  },
  {
    id: "AO-2025-018",
    title: "EnergyDataOps — Transformation Data & IA des actifs renouvelables",
    client: "ENGIE SA",
    sector: "Énergie et utilities",
    status: "won",
    consultantsNeeded: 6,
    price: 1205715,
    tags: ["Data", "IA", "Cloud", "IoT"],
    similarityScore: 62,
    submissionDate: "2025-04-18",
    responseDate: "2025-05-15",
    description: "Proposition Wavestone — Transformation Data & IA des actifs renouvelables ENGIE avec l'approche EnergyDataOps. Architecture Data Lake Azure native et modèles IA spécialisés utilities.",
    aiSummary: "EnergyDataOps — approche propriétaire développée sur 8 projets utilities. Architecture Data Lake Azure Data Lake Storage Gen2 + Azure Data Factory. Traitement temps réel via Azure Stream Analytics (5 000+ capteurs). RMSE J+1 cible 4,5% (LSTM+XGBoost). Maintenance prédictive onshore (SAP PM). Tableau de bord Power BI Embedded unifié. Références : RTE (dispatch -8% coûts congestion), Enedis (35M compteurs Linky, Data Lake temps réel), Neoen (18 parcs, RMSE 4,8%).",
    methodology: "EnergyDataOps — 5 phases sur 52 semaines. Phase 1 : Audit & Cartographie data SCADA (Sem. 1-8). Phase 2 : Architecture Data Lake Azure ADLS API SCADA IEC 61968 (Sem. 9-16). Phase 3 : Modèles IA prédiction LSTM XGBoost NWP RMSE<4,5% (Sem. 17-28). Phase 4 : Maintenance prédictive & Dashboard opérationnel (Sem. 29-44). Phase 5 : Formation & Transfert de compétences ENGIE (Sem. 45-52).",
    staffing: "Sébastien MOULIN (Directeur de mission, 15 ans, Énergie RTE Enedis programme, 80%), Claire FONTAINE (Chef de projet senior, 10 ans, PMP Agile utilities Azure, 100%), Julien MERCIER (Architecte Data Azure, 9 ans, Azure Data Factory ADLS SCADA IEC 61968, 100%), Amina BENALI (Data Scientist Énergie, 7 ans, LSTM XGBoost NWP séries temporelles, 80%), Hugo PERRIN (Expert Jumeaux Numériques, 5 ans, MATLAB Simulink modélisation physique, 60%), Lucie THOMAS (DevOps Azure, 5 ans, Azure Kubernetes CI/CD Terraform, 80%)",
    differentiators: "120 consultants spécialisés Énergie & Utilities. Références Enedis (35M compteurs Linky) et RTE (dispatch réseau). Expertise Azure DataOps native. Budget compétitif 1,2M€ HT sous le plancher de l'AO. Approche centrée sur la qualité des données dès la collecte.",
    duration: "30 mois",
    technologies: ["Azure"],
  },
  {
    id: "AO-2025-019",
    title: "Cloud-First AI Transformation pour les actifs énergétiques ENGIE",
    client: "ENGIE SA",
    sector: "Énergie et utilities",
    status: "lost",
    consultantsNeeded: 6,
    price: 2802850,
    tags: ["Cloud", "IA", "Infrastructure"],
    similarityScore: 42,
    submissionDate: "2025-04-18",
    responseDate: "2025-05-15",
    description: "Proposition Accenture — Transformation Cloud & IA généraliste des actifs énergétiques ENGIE via la plateforme myWizard Energy sur AWS. Approche généraliste avec accélérateurs IA pré-construits.",
    aiSummary: "Plateforme myWizard Energy sur AWS — accélérateurs IA pré-construits réduisant de 40% le temps de déploiement. Jumeaux numériques via AWS IoT TwinMaker. RMSE J+1 estimé à 5,5% (entraînement 5 ans). Maintenance prédictive via Amazon SageMaker. Références : BP offshore (30 plateformes, -18% pannes), Iberdrola cloud migration AWS (2 000+ turbines), E.ON maintenance prédictive SageMaker.",
    methodology: "myWizard Energy Platform — 4 phases sur 48 semaines. Phase 1 : Discovery & Cloud Assessment, audit SI cartographie actifs roadmap cloud AWS (Sem. 1-8). Phase 2 : Cloud Migration & Data Platform, migration AWS Data Lake API layer (Sem. 9-20). Phase 3 : IA & Digital Twins, modèles ML AWS IoT TwinMaker dashboards (Sem. 21-32). Phase 4 : Scale & Operate, déploiement global MLOps support (Sem. 33-48).",
    staffing: "Marie-Christine LEBLANC (Managing Director, 20 ans, énergie mondiale AWS transformation, 50%), Paul HERNANDEZ (Delivery Lead, 13 ans, AWS cloud migration Agile at scale, 100%), Sandra OKONKWO (Data Scientist, 8 ans, ML Python time series NLP, 80%), Kevin MULLER (Architecte Cloud AWS, 9 ans, AWS IoT TwinMaker Lambda SageMaker, 100%), Céline ROUSSEAU (Expert Change & Training, 7 ans, formation adoption digitale LMS, 60%), Thomas PHAM (DevOps Engineer, 6 ans, AWS Terraform CI/CD Kubernetes, 80%)",
    differentiators: "Leader mondial du conseil et services numériques, 750 000 collaborateurs. 12 000 experts Energy mondiaux. 200+ transformations digitales secteur énergie. Plateforme myWizard Energy avec accélérateurs pré-construits. Déploiement rapide garanti.",
    duration: "30 mois",
    technologies: ["AWS"],
  },
  {
    id: "AO-2025-020",
    title: "Modernisation du système d'information corporate ENGIE",
    client: "ENGIE SA",
    sector: "Énergie et utilities",
    status: "lost",
    consultantsNeeded: 5,
    price: 1875300,
    tags: ["ERP", "SAP", "Change Management", "RGPD"],
    similarityScore: 22,
    submissionDate: "2025-04-18",
    responseDate: "2025-05-15",
    description: "Proposition Sopra Steria — Modernisation du SI corporate ENGIE via migration SAP S/4HANA. Approche ERP & Gouvernance SI très éloignée des besoins IoT/IA de l'AO. Expertise ERP et conformité réglementaire.",
    aiSummary: "Integrated Digital Core — méthodologie SAP S/4HANA 15 ans d'expérience grands comptes. Migration ERP financier et RH. MDM pour unifier référentiels clients/fournisseurs/actifs. RGPD cartographie flux de données. Reporting ESG CSRD. Références : TotalEnergies SAP S/4HANA (12 filiales, 3 200 users, -40% délais clôture), EDF gouvernance données (MDM RGPD NIS2), ENGIE corporate reporting ESG CSRD.",
    methodology: "Integrated Digital Core — 4 phases sur 48 semaines. Phase 1 : Audit & Business Blueprint, cartographie processus gap analysis SAP (Sem. 1-10). Phase 2 : Configuration & Paramétrage SAP S/4HANA Finance HR Procurement (Sem. 11-24). Phase 3 : Tests & Recette, UAT tests de charge correction anomalies (Sem. 25-36). Phase 4 : Déploiement & Go-Live, bascule progressive hypercare 3 mois (Sem. 37-48).",
    staffing: "François BERTRAND (Directeur de mission, 18 ans, SAP Énergie programme grands comptes, 100%), Isabelle MARCHAL (Chef de projet ERP, 12 ans, SAP S/4HANA PRINCE2 Agile, 100%), David KOWALSKI (Architecte SAP, 10 ans, S/4HANA BTP MDM intégration SI, 100%), Nathalie VIDAL (Experte Conformité & RGPD, 9 ans, DPO CNIL NIS2 audit SI, 80%), Romain CHARTIER (Consultant Change Mgmt, 7 ans, formation conduite du changement ERP, 60%)",
    differentiators: "55 000 collaborateurs, leader européen transformation numérique. 20 ans d'expérience ERP grands comptes énergie. Expertise SAP S/4HANA certifiée. Connaissance réglementaire RGPD/NIS2/CSRD. Proposition très éloignée des besoins IoT/IA de l'AO.",
    duration: "30 mois",
    technologies: ["SAP"],
  },
];

// Monthly evolution data for charts
export const monthlyEvolution = [
  { month: "Jan", won: 3, lost: 1 },
  { month: "Fév", won: 2, lost: 2 },
  { month: "Mar", won: 4, lost: 1 },
  { month: "Avr", won: 2, lost: 3 },
  { month: "Mai", won: 5, lost: 1 },
  { month: "Jun", won: 3, lost: 2 },
  { month: "Jul", won: 4, lost: 1 },
  { month: "Aoû", won: 2, lost: 2 },
  { month: "Sep", won: 5, lost: 1 },
  { month: "Oct", won: 3, lost: 3 },
  { month: "Nov", won: 6, lost: 1 },
  { month: "Déc", won: 4, lost: 2 },
];

// Sector distribution
export const sectorDistribution = sectors.map((sector) => ({
  name: sector,
  value: tenders.filter((t) => t.sector === sector).length,
  won: tenders.filter((t) => t.sector === sector && t.status === "won").length,
}));

// Recent activity
export const recentActivity = [
  { id: 1, action: "Réponse soumise", tender: "AO-2025-016", time: "Il y a 2h", type: "submit" as const },
  { id: 2, action: "Appel d'offres gagné", tender: "AO-2025-014", time: "Il y a 5h", type: "won" as const },
  { id: 3, action: "Nouveau document uploadé", tender: "AO-2025-008", time: "Il y a 1j", type: "upload" as const },
  { id: 4, action: "Analyse IA terminée", tender: "AO-2025-016", time: "Il y a 1j", type: "ai" as const },
  { id: 5, action: "Appel d'offres perdu", tender: "AO-2025-015", time: "Il y a 2j", type: "lost" as const },
];
